AWSTemplateFormatVersion: '2010-09-09'
Description: '3 Private S3 Buckets with versioning enabled'

Parameters:
  ProjectName:
    Type: String
    Default: 'nm1811-cloudformation'
    Description: 'Project name for resource naming'
  
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - test
      - prod
    Description: 'Environment type'

Resources:
  S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-bucket-1-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bucket-1'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'PROG8870-CloudFormation'

  # S3 Bucket 2
  S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-bucket-2-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bucket-2'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'PROG8870-CloudFormation'

  # S3 Bucket 3
  S3Bucket3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-bucket-3-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bucket-3'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'PROG8870-CloudFormation'

Outputs:
  S3Bucket1Name:
    Description: 'Name of S3 Bucket 1'
    Value: !Ref S3Bucket1

  S3Bucket2Name:
    Description: 'Name of S3 Bucket 2'
    Value: !Ref S3Bucket2

  S3Bucket3Name:
    Description: 'Name of S3 Bucket 3'
    Value: !Ref S3Bucket3

  S3BucketArns:
    Description: 'ARNs of all S3 Buckets'
    Value: !Sub 
      - '${Bucket1Arn}, ${Bucket2Arn}, ${Bucket3Arn}'
      - Bucket1Arn: !GetAtt S3Bucket1.Arn
        Bucket2Arn: !GetAtt S3Bucket2.Arn
        Bucket3Arn: !GetAtt S3Bucket3.Arn
        